### ISSUE TITLE
Create and upload a snapshot when a file is added to a magic-folder

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#109]
The watchdog system should trigger a file modified/created event and that would put an item into the queue that eventually create an in-memory representation of the snapshot and an on-disk representation so that even if the computer crashes or we lose network connectivity, we maintain the ability to recreate history of the changes. These local snapshot representation is later "committed" to the grid. 

So, this task comprise of these separate tickets:

- [ ] [Observe File Addition](https://github.com/LeastAuthority/magic-folder/issues/138).
- [x] [Python API to manually add files to upload queue](https://github.com/LeastAuthority/magic-folder/issues/161).
- [x] [Create in-memory representation of the Local Snapshot](https://github.com/LeastAuthority/magic-folder/issues/139).
- [x] [Create on-disk representation of the Local Snapshot](https://github.com/LeastAuthority/magic-folder/issues/140).
- [x] [Commit the Local Snapshot to the grid](https://github.com/LeastAuthority/magic-folder/issues/141).
- [x] [Add an HTTP API to create a local snapshot of a file](https://github.com/LeastAuthority/magic-folder/issues/266).
- [x] [Process local snapshots into remote snapshots](https://github.com/LeastAuthority/magic-folder/issues/265)
- [x] [Add verified-fakes hot fix to magic-folder repo](https://github.com/LeastAuthority/magic-folder/issues/142).

**Comment by meejah** [comment]
I wonder if it would be "easier" (less work) to make the "Observe Filesystem Changes" into the "API" version? (That is, "provide an API that tells us to queue a particular file for creation of a new snapshot").

From recent discussion it sounds like users might want more control of this *anyway*. Another "pro" is that I think it'll be easier to test an API-based Snapshot creator rather than faking out what watchdog (or whatever) does. Then the "Observe Filesystem Changes" part can be a followup (and use the API, even).

**Comment by vu3rdd** [comment]
@meejah That sounds like a good idea. 

Also, just for the purpose of writing this down more explicitly, the flow would be:

1. Observe file addition (either via API or via watchdog)
2. If watchdog triggered them, call the API to queue these additions.
3. Create local snapshots.
4. Persist these snapshots to the disk.
5. Simultaneously push these snapshots into a queue.
6. The queue is emptied to "commit" the Local Snapshots into the grid and these become "Remote Snapshots".
7. Update the sqlite to add/update the local_files entry for the relative file path with the latest snapshot URI.
