### ISSUE TITLE
magic_folder.test.no_network should no longer be required

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#22]
The unit test suite doesn't need to set up a "no network" Tahoe-LAFS grid and the integration tests don't use this approach (preferring to set up a network-using grid).

This module should go and anything that is still using it is bogus and needs to be fixed.

This looks like it is too large to do all at once so here are some sub-tasks:

- [x] magic_folder.test.cli.test_magic_folder.ListMagicFolder - #30 
- [x] magic_folder.test.cli.test_magic_folder.StatusMagicFolder - #33 
- [x] magic_folder.test.cli.test_magic_folder.CreateMagicFolder - #47 
- [ ] magic_folder.test.test_magic_folder.RealTest
- [ ] magic_folder.test.test_magic_folder.RealTestAliceBob
- [ ] magic_folder.test.test_magic_folder.MockTest
- [ ] magic_folder.test.test_magic_folder.MockTestAliceBob

**Comment by meejah** [comment]
It is gone.
